# Generated by Django 4.0.3 on 2022-05-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsVoited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('is_voted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Kondorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place1', models.CharField(max_length=50)),
                ('place2', models.CharField(max_length=50)),
                ('place3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partA', to='mainapp.part')),
                ('partB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partB', to='mainapp.part')),
                ('partC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partC', to='mainapp.part')),
            ],
        ),
    ]
